# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='codigo_postal',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='concepto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='direccion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='google_plus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='linkein',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='telefono',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='historia',
            field=models.TextField(null=True),
        ),
    ]
