# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-22 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20160722_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='linkein',
            new_name='linkedin',
        ),
    ]
